### ISSUE TITLE
Saving Preferences in the new versions 60.3.0 wont remember settings, wont save

### ISSUE THREAD

**Issue by warclaws** [jikamens/reply-to-multiple-messages#5]
When trying to save a preference in Thunderbird, the extension reply-to-multiple messages doesnt save settings. I keep saving "BCC only" and come back and the check mark is gone.  It wont save it!

**Comment by jikamens** [comment]
Please confirm that you are using the current version of Reply To Multiple Messages. This issue is fixed in version 1.0.5, which was released a couple of weeks ago. Reopen if you're still having this issue with version 1.0.5.

**Comment by warclaws** [comment]
*When I go into the preference box, BCC is unchecked, but it is still
working on machines with that preference being used prior... but on new
machines we put thunderbird on and use the extension, it doesnt save and
allow us to use BCC*

**Comment by warclaws** [comment]
*When I go into the preference box, BCC is unchecked, but it is still
working on machines with that preference being used prior... but on new
machines we put thunderbird on and use the extension, it doesnt save and
allow us to use BCC*

*Jeff Spreen*

*Dealer Principal*
*Spreen Honda | Acura | Mazda**Office 909-740-6161*

**Comment by jikamens** [comment]
**sigh** I just noticed that the editors of addons.thunderbird.net haven't approved release 1.0.5 even though it's been in the approval queue for more than two weeks. I have no idea why; other releases I've submitted since then have been approved.

I unfortunately have no control over this. I've sent them a message asking about the delay, but I don't know when / whether they'll reply or when they'll approve the new version.

In the meantime, you can download the fixed version from https://addons.thunderbird.net/thunderbird/downloads/file/1012005/reply_to_multiple_messages-1.0.5-sm+tb.xpi.

**Comment by warclaws** [comment]
Thank you

**Comment by chrizilla** [comment]
>@jikamens: in the approval queue for more than two weeks. I have no idea why

see: https://bugzilla.mozilla.org/show_bug.cgi?id=1499602#c3
